<script setup lang="ts">
    import { useLoading } from '../store/loading';

    const { loading } = useLoading();
</script>

<template>
    <div v-if="loading.length" class="c-loading__container">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; display: block; shape-rendering: auto;" width="80px" height="80px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <g transform="rotate(0 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.9716599190283399s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(27.692307692307693 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.8906882591093116s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(55.38461538461539 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.8097165991902833s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(83.07692307692308 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.7287449392712549s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(110.76923076923077 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.6477732793522266s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(138.46153846153845 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.5668016194331983s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(166.15384615384616 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.48582995951416996s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(193.84615384615384 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.40485829959514164s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(221.53846153846155 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.3238866396761133s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(249.23076923076923 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.24291497975708498s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(276.9230769230769 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.16194331983805665s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(304.61538461538464 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="-0.08097165991902833s" repeatCount="indefinite"></animate>
            </rect>
            </g><g transform="rotate(332.3076923076923 50 50)">
            <rect x="48" y="22.5" rx="2" ry="3.25" width="4" height="13" fill="#ffffff">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.0526315789473684s" begin="0s" repeatCount="indefinite"></animate>
            </rect>
            </g>
            <!-- [ldio] generated by https://loading.io/ -->
        </svg>
    </div>
</template>
